repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
        args: [--config=pyproject.toml]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
        args: [--config=pyproject.toml]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        require_serial: true
        args: [--settings-path=pyproject.toml]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        require_serial: true
        args: [--config-file=pyproject.toml]
